version: "3.8"

services:
  autoplaywright:
    build: .
    volumes:
      - ./test-results:/app/test-results
      - ./specs:/app/specs
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: node tests/runRoutes.js
