services:
  autoplaywright:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./test-results:/app/test-results
      - ./specs:/app/specs
      - ./test_point:/app/test_point
      - ./cache:/app/cache
      - ./config.json:/app/config.json
      - ./credentials.json:/app/credentials.json:ro  # Google Sheets API認証ファイル（読み取り専用）
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=/app/airy-cycle-451111-s0-32fbfd2f1e9f.json
      - ALLOW_EXTERNAL_ACCESS=false
    command: node server.js
