version: "3.8"
services:
  test:
    build: .
    volumes:
      - .:/app
      - ~/.aws:/root/.aws:ro
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/credentials.json

  autoplaywright:
    build: .
    volumes:
      - ./test-results:/app/test-results
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: node tests/runRoutes.js
